### PR TITLE
Add crafting step list

### LINKED ISSUE #15: Suggestion: Crafting List
An alternative to a tech tree would be a list of crafting recipes used to create a given item. It would look like this:

```
B + D = E
C + C = D
A + B = C
A + A = B
```

This wouldn't take much horizontal room and therefore be ideal on a mobile device. The tech tree would be difficult to display on a mobile device.

### PR DESCRIPTION
**Pull request by ryanb**
The Crafting Steps list is an alternative to the tech tree. A button is added next to the tech tree:

screen shot 2018-04-13 at 3 14 00 pm

Clicking that will show you the steps required to craft the item.

screen shot 2018-04-13 at 3 13 05 pm

Each step tells you what is needed for the next step. Longer steps are split up (a, b, c) for easier reading.

Benefits over the tech tree:
* See more steps at once
* Mobile friendly
* Fewer duplicates
* See how many you need of item (coming soon)
  * This will be easy to add once #48 is merged

It shows up to ~35 transitions.

What do you think?

Closes #15

### CODE REVIEW

**Comment by Kazetsukai** [comment]
How does it handle infinite loops? I think there were a couple in the tech
trees

**Comment by Kazetsukai** [comment]
It's a little confusing to me in a couple of places. i.e. Step 4 is asking you to take a branch off a tree to make an empty tree for step 5? I don't think that particular step is avoidable for an auto generated step list, but maybe it would be nice to have a ist of "Things you are expected to have at the end of this step"?

Also this might be an annoying change to make, but I don't think the card layout shows a linear flow very well. I imagine this looks great on mobile with one column of cards, but I almost feel that the step cards should always be in one column, and should grow on desktop by fitting more individual parts of the steps in each row. Then the end of each step could show a list of items you should have. This should make it a little more of a "Ok I have done all the bits for this step, now I scroll down" rather than "now I try to remember that I am on the middle step on the screen"

Here's a super rough example of what I am thinking: 
image

**Comment by Kazetsukai** [comment]
The other benefit of doing it like this, is if someone knows a lot of recipes off by heart, they just need to look at the ingredients needed at each step first, then only look back to the individual recipes for things they don't know how to get. Could put numbers like "x3" on these as well, which would get at what you were talking about around seeing the total amount of resources needed to craft something.

**Comment by ryanb** [comment]
I originally had the step span the full width but I didn’t like how the transitions were not lined up. At the time they varied in width so I will try this again and it will probably be better now that they are consistent.

It will also be nice to have the full step shown instead of splitting it up.

Regarding showing the resulting items. This will always match the result of each transition. It also matches the requirements of the following step transitions (except for natural spawned objects). I will give it a try though.

**Comment by ryanb** [comment]
I went through a few different options and labeled them in commits. Feel free to check out the commit and play around with them.

### Option 1: Wide step
screen shot 2018-04-16 at 9 28 41 am

### Option 2: Wide step with results
screen shot 2018-04-16 at 9 43 45 am

### Option 3: Narrow step with results and Show Details button

Clicking the button shows the transitions needed for the objects.

screen shot 2018-04-16 at 10 07 51 am

### Option 4: Narrow step with selectable objects

Clicking an object will select it and show the recipe below. You can select multiple objects and multiple transitions will be shown.

screen shot 2018-04-16 at 10 24 09 am

### Option 5: Wide step with selectable objects

Like option 4 but wide steps.

screen shot 2018-04-16 at 10 51 30 am

Options 4 and 5 are nice because they show minimal information. The user can click whichever objects they don't know how to make to see the recipe.

However, they might show too less information at first because it may not be obvious that the array of objects shown are separate objects that should be crafted to move onto the next step.

Any ideas?

**Comment by ryanb** [comment]
Thinking about this more, perhaps part of the confusion isn't how steps are presented, but how they are generated to begin with. The step list starts to break down on anything more complex than Fire because each step is making several objects concurrently.

Ideally, the step list would present instructions in the order the player would do them in. Getting a Butt Log shouldn't require several steps where each one is removing a piece of firewood. Decay transitions shouldn't be spread out. Making a shovel head shouldn't divide each hammer hit into a separate step.

I tried to fix some of this by collapsing steps with a single transition and chains of decay transitions but it isn't enough. Instead transitions could be collapsed if it:
* has a decay timer
* targets ground (placing items down)
* uses the same tool multiple times
* has a much simpler complexity from the main object

Perhaps we should take a few example scenarios and think of the ideal step list and then see how we can get there.

**Comment by Kazetsukai** [comment]
Definitely like the suggestion of pulling out the tools. Most recipes look really complicated because of the tools being included.

Beyond that, if selecting still feels relevant, I don't really like the selecting of individual items to expand their recipe. I would prefer to expand and collapse all the recipes inside one step, if we need that at all. Definitely try the tool idea first.

**Comment by ryanb** [comment]
Wow, pulling out the tools really helped. I also stopped merging single-transition steps because it caused confusion. The requirements for each recipe are now listed at the top.

screen shot 2018-04-17 at 10 32 46 am

Very rarely does a step go beyond 3 transitions. Perhaps I should compact the steps list and show a number on the side instead of at the top?

I need to do some code cleanup, and will probably rename Steps List to Recipe. I'm pretty happy with how this is turning out now.

**Comment by Kazetsukai** [comment]
Beautiful, nice work!

**Comment by ryanb** [comment]
I compacted the steps list and renamed it to Recipe. Here it is on desktop and mobile.

screen shot 2018-04-18 at 9 54 40 am

screen shot 2018-04-18 at 9 44 25 am

How's this?

**Comment by ryanb** [comment]
I'll get this merged in, here's the updated visuals:

screen shot 2018-04-19 at 8 23 51 am

I like it! Feel free to adjust things in master.

**Pull request merged**
