### PR TITLE
Add router with improved SEO support

### LINKED ISSUE #78: Poor SEO
This isn't very crawler friendly at the moment. Google and others have some trouble with SPAs. Searching something like "one hour one life craft door" has the site show up pretty far down, and doesn't go directly to the page. Some resources:

* https://moz.com/blog/optimizing-angularjs-single-page-applications-googlebot-crawlers
* https://vuejsdevelopers.com/2018/04/09/single-page-app-seo/
* https://vuejsdevelopers.com/2017/04/01/vue-js-prerendering-node-laravel/
* https://github.com/rafrex/spa-github-pages
* https://github.com/isaacs/github/issues/408

### PR DESCRIPTION
**Pull request by ryanb**
* vue-router is used in history mode
  * This means no more hash based URLs
* vue-meta is used for changing the page title
* The old hash URLs are redirected to the new format
* `404.html` file redirects to `index.html` according to [this workaround](https://github.com/rafrex/spa-github-pages)
* `sitemap.xml` and `robots.txt` added
* Process script generates `sitemap.xml`

Closes #78

### CODE REVIEW

**Comment by ryanb** [comment]
@Kazetsukai after merging this in, would you mind copying the robots.txt file to [kazetsukai.github.io](https://github.com/Kazetsukai/kazetsukai.github.io)? This way it will be found at the root.

**Comment by Kazetsukai** [comment]
Yep, will do that when I get a moment.

**Comment by Kazetsukai** [comment]
Am moving house so fumbling through on my phone, but I think I have the
robots.txt in place.

**Comment by ryanb** [comment]
I went ahead and merged this in today and deployed. I noticed a bug with the router so I reverted the deploy, fixed, then deployed again. It all seems to be working now. I hope this resolves the SEO issues.

**Pull request merged**
