### PR TITLE
Adding biomes and spawn chance data

### PR DESCRIPTION
**Pull request by ryanb**
This adds a "Spawn Chance" and "Biome" stat to the natural spawning objects:

screen shot 2018-04-10 at 8 39 57 am

I'm not certain how the `mapChance` is used. Should it be displayed as a percentage? So 0.1 would be 10%.

### CODE REVIEW

**Comment by Kazetsukai** [comment]
I wonder if we could use a fixed bucketing for this. Have a look at the spread of chances, and say "Common", "Uncommon", "Rare" etc

I don't think a relative bucketing like you used for complexity will work quite as well here, but since the chances seem to be in a fixed range it should be straightforward to hardcode labels for ranges.

**Comment by ryanb** [comment]
Do you think we should incorporate the ground images with this? It might be more clear than saying “prairie”

Also when we add a “how to get” section we could display the natural spawn details there.

**Comment by Kazetsukai** [comment]
Absolutely. Early on I was thinking of putting the spawn biome's background
as a background on each item, although that may distract too much from the
items, haven't tried yet.

**Comment by ryanb** [comment]
I changed it to show spawn chance as: Common, Uncommon, Rare and Very Rare with a tooltip showing the percent chance.

screen shot 2018-04-15 at 2 07 38 pm

Does that sound good for now? Maybe we can add the biome images once we do #6

**Comment by Kazetsukai** [comment]
Oh do we know that 0.1 means 10% chance from the code?

10% per what? Square? Surely not?

**Comment by ryanb** [comment]
I believe `mapChance` is the chance the object has to spawn once it has been chosen for a given tile. I haven’t dived into the code enough to determine how objects are chosen.

**Comment by Kazetsukai** [comment]
My preference would be to call it "very rare" as you have, and leave the ? circle out altogether as I don't think mousing over it clarifies much. Definitely like the rarity label though.

I think 10% is probably too high for the label "Very Rare" though, so maybe just split it into three (0 - 33% is rare, 34% - 66% is uncommon, everything above is common). If it works how I think, and it would mean "For every 10 reeds, there would be 1 horse" then that sounds rare but not very rare.

**Comment by Kazetsukai** [comment]
Or even, set the labels array to be:

    [Very Rare, Rare, Rare, Uncommon, Uncommon, Uncommon, Uncommon, Common, Common, Common, Common, Common, Common, Common, Common]

as a cheap way of splitting up the range non-linearly.

**Pull request merged**
