### PR TITLE
Object Model Refactoring

### PR DESCRIPTION
**Pull request by ryanb**
Note: This includes PR #30 to avoid conflicts. Please address that one first.

This is a fairly large refactoring of the client app. The motivation is to reduce the size of the JSON data. It does this by using object ids which are mapped to an object instance on the client side. A `GameObject` model class has been added to unify the Object logic and data fetching. Some highlights:

* `objects.json` is about half the size
* `objects/#id.json` is about a quarter of the size
* Object data is remembered so revisiting an object is instant
* Removed global navigation mixin in favor of `object.url()`
* Added `TechTreeView` component which cleans up the tech tree significantly
* Fixed `numUses` check in `TransitionView`
* Show number of uses in object inspector

I have mixed feelings about this `GameObject` model. It feels a little wrong to have Vue components observe object instances instead of simple data. I'm not familiar enough with Vue to know what the best practice is here. What do you think?

### CODE REVIEW

**Comment by Kazetsukai** [comment]
Going to have to look at this when I get back from friend's wedding. My suspicion so far is that it is precisely through observing object instances that gives Vue a lot of power around nested components. Might be misunderstanding what you mean.

**Comment by ryanb** [comment]
What I mean is, does Vue accurately reach through a method to determine when to update? For example:

```vue
<div v-if="object.isLoaded()"></div>

// in object
isLoaded () {
  return this.data !== null;
}
```

Verses working on simple data:

```vue
<div v-if="object.data"></div>
```

I've also ran into some issues where `data` is not observed if it is undefined. I need to set it to `null` before the component mounts.

I'm a little more familiar with React where it is better to make a separate component for fetching the data which renders a simple view component. Not certain if this best practice applies to Vue as well.

This project is probably simple enough to leave as is, but I'm using it as a bit of a playground to learn Vue and try ideas. Hope you don't mind. :)

**Comment by ryanb** [comment]
@Kazetsukai do you prefer to work directly on `prototype`? Or avoid classes altogether?

I'll merge this so I can make changes without conflicting with this. I'm up for changing it though.

**Comment by Kazetsukai** [comment]
Again I haven't done enough JS to have strong opinions. They feel a little deceptive in that they are just syntactic sugar over prototypes right? I suspect I would be a lot happier if the syntax looked exactly as it does now, but they used the keyword "prototype" instead of "class".

**Pull request merged**
