### PR TITLE
Adding insulation info to inspector

### LINKED ISSUE #13: Add Insulation Stat to Clothing
Add a stat to the Object Inspector showing how much clothes insulate you.

### PR DESCRIPTION
**Pull request by ryanb**
Closes #13

### CODE REVIEW

**Comment by Kazetsukai** [comment]
What does rValue mean? Heat and food are bad enough, but this in particular I think we at least need a brief description in a tooltip or similar.

**Comment by ryanb** [comment]
It is pretty complicated. This post explains it.

https://onehouronelife.com/forums/viewtopic.php?pid=3112#p3112

I think this stat is useful to display to compare clothing but I don’t know how to present it in a good way.

**Comment by Kazetsukai** [comment]
Right, so a piece of clothing "Reduces heat loss by ( (1-rValue) * slotCoefficient * 100) percent"

**Comment by ryanb** [comment]
How about displaying it like this?

Insulation: 90% Head (32% Body)

**Comment by ryanb** [comment]
Updated the code to show percents of part and body:

screen shot 2018-03-21 at 9 22 29 am

It looks a little busy, but the information makes more sense.

**NOTE:** You'll need to run the process script since this doesn't include the `static` changes. I won't be including those in PRs now.

**Comment by Kazetsukai** [comment]
I think that is a little deceptive, because the wolf hat should be the
inverse if I understand correctly. It lowers heat loss by 10% multiplied by
slot right?

**Comment by ryanb** [comment]
The post I linked on the forum is incorrect. The higher `rValue` the warmer it keeps you. I think what I have is correct but I don't fully understand the code.

**Comment by Kazetsukai** [comment]
Ah ok, looks pretty good then. Maybe we just show the final total though? "Insulation: 23%" to keep it simple? Should make it easier to compare a hat to a shoe at a glance.

**Comment by ryanb** [comment]
I simplified the insulation stat and added a clothing type stat.

screen shot 2018-03-21 at 2 49 13 pm

Some clothing isn't obvious what part it covers (such as the mouflon hide).

**Comment by Kazetsukai** [comment]
Nice work 👍

**Pull request merged**
