### PR TITLE
Redesign Object Inspector

### LINKED ISSUE #6: Recipe cards are confusing
The 4 corner layout I made for the recipe cards is confusing. Would be better to lay out the recipes as rows, with 4 squares going across, ideally center justified as so:

    #+# > # #
      # > # #
    #+# > #

### PR DESCRIPTION
**Pull request by ryanb**
Changes to object inspector:
* Transitions moved to the right side
* Timed transitions shown separately
* Titles for each section: "How to get", "How to use" and "Timed transitions"
* "Show more..." link when more than 3 transitions

screen shot 2018-04-22 at 10 38 55 am

screen shot 2018-04-22 at 10 39 45 am

Any suggestions?

Closes #6

### CODE REVIEW

**Comment by Kazetsukai** [comment]
Nice. This is pretty much what I was imagining. When there is only one item on the left side of a transition does it align to the center?

I do want to avoid the term "transitions" as I think it is an internal term that most people playing the game won't know. Maybe "Changes over time"?

**Comment by ryanb** [comment]
> Nice. This is pretty much what I was imagining. When there is only one item on the left side of a transition does it align to the center?

Yep, I just put some padding in there when only one.

screen shot 2018-04-22 at 2 49 55 pm

> I do want to avoid the term "transitions" as I think it is an internal term that most people playing the game won't know. Maybe "Changes over time"?

This is updated. Do you think transitions which change to the current object should be shown in the "How to get" section instead? Wasn't sure about this.

**Comment by Kazetsukai** [comment]
Yeah, timed transitions away really don't come under "How to use", but I think transitions in do count as "how to get", so yeah moving them under that header sounds like a good idea.

The whole cycle of the goose in the pond is a little strange (who cares about 'getting' a pond with a goose in it?), but I don't think there is a simple programmatic way to combine all of those into one "thing" or differentiate from things people do care about getting, so it is only a minor inconvenience. I think all the animals tend to have this issue, because we think of them as one "thing" with different states, while the game treats them as different objects.

**Comment by ryanb** [comment]
Cool. I will make this change and get it merged in a bit later.

**Comment by Kazetsukai** [comment]
Nicely done

**Pull request merged**
